version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /fronted
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
